version: '3.7'

services:
  db:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      # If the secret key contains a $ then add an additional dollar sign $$
      - SECRET_KEY=n78##rt74prpa_757i!np8x94%dfcph*28mzek$$*2i8^*2ymg&
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
    postgres_data:
